Repository RodrigoCapreDev/eventhub, pull requests merged in 2025-06, with the labels that each got.

#11 docs: actualizar README con convenciones de ramas
  README.md
Labels: documentation

#13 fix: refactor de tests y lógica de eventos pasados para evitar falsos positivos en la feature 2
  app/models.py
  app/test/test_integration/test_event.py
  app/test/test_unit/test_event.py
  app/views.py
Labels: bug

#14 Infra: Crear y optimizar Dockerfile para aprovisionamiento #10
  .dockerignore
  .env.example
  Dockerfile
  eventhub/settings.py
  requirements.txt
Labels: enhancement, infra

#18 Infra: configurar ci
  .github/workflows/ci.yml
Labels: enhancement, infra

#20 Infra/#19 configurar cd
  .github/workflows/cd.yml
Labels: enhancement, infra

#22 infra: Configurar CD para Deploy Continuo #21
  .github/workflows/cd.yml
Labels: enhancement, infra

#26 infra: Configura WhiteNoise y recolecta archivos estáticos en Docker
  Dockerfile
  eventhub/settings.py
  requirements.txt
Labels: bug, enhancement, infra

#27 fix: implementar render hook en CD
  .github/workflows/cd.yml
Labels: bug, infra
